export const PRIZE_MANIFEST = [
  {
    id: "cube_bunny",
    name: "小兔玩偶",
    url: "/assets/models/3d/prizes/animal-bunny.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 8,
    maxPerRound: 2,
    targetHeight: 0.82,
    groundOffset: 0,
    grabRadius: 0.5,
    grabOffset: [0, 0.56, 0],
    collider: { type: "box", size: [0.58, 0.72, 0.54] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
    colorVariants: ["cream", "pink", "sage"],
  },
  {
    id: "cube_cat",
    name: "小猫玩偶",
    url: "/assets/models/3d/prizes/animal-cat.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 7,
    maxPerRound: 2,
    targetHeight: 0.82,
    groundOffset: 0,
    grabRadius: 0.5,
    grabOffset: [0, 0.55, 0],
    collider: { type: "box", size: [0.58, 0.72, 0.54] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
    colorVariants: ["cream", "orange", "lavender"],
  },
  {
    id: "cube_dog",
    name: "小狗玩偶",
    url: "/assets/models/3d/prizes/animal-dog.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 7,
    maxPerRound: 2,
    targetHeight: 0.8,
    groundOffset: 0,
    grabRadius: 0.5,
    grabOffset: [0, 0.54, 0],
    collider: { type: "box", size: [0.58, 0.7, 0.54] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
    colorVariants: ["caramel", "cream", "blue"],
  },
  {
    id: "cube_panda",
    name: "熊猫玩偶",
    url: "/assets/models/3d/prizes/animal-panda.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 7,
    maxPerRound: 2,
    targetHeight: 0.82,
    groundOffset: 0,
    grabRadius: 0.51,
    grabOffset: [0, 0.56, 0],
    collider: { type: "box", size: [0.6, 0.72, 0.55] },
    scaleRange: [0.9, 1.06],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "cube_penguin",
    name: "企鹅玩偶",
    url: "/assets/models/3d/prizes/animal-penguin.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 6,
    maxPerRound: 2,
    targetHeight: 0.82,
    groundOffset: 0,
    grabRadius: 0.48,
    grabOffset: [0, 0.55, 0],
    collider: { type: "box", size: [0.56, 0.72, 0.52] },
    scaleRange: [0.9, 1.08],
    rotationRange: { x: [-0.08, 0.08], y: [-Math.PI, Math.PI], z: [-0.12, 0.12] },
  },
  {
    id: "cube_tiger",
    name: "小虎玩偶",
    url: "/assets/models/3d/prizes/animal-tiger.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 6,
    maxPerRound: 2,
    targetHeight: 0.84,
    groundOffset: 0,
    grabRadius: 0.52,
    grabOffset: [0, 0.57, 0],
    collider: { type: "box", size: [0.62, 0.74, 0.56] },
    scaleRange: [0.9, 1.06],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "cube_fox",
    name: "小狐玩偶",
    url: "/assets/models/3d/prizes/animal-fox.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 6,
    maxPerRound: 2,
    targetHeight: 0.82,
    groundOffset: 0,
    grabRadius: 0.5,
    grabOffset: [0, 0.55, 0],
    collider: { type: "box", size: [0.58, 0.72, 0.54] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "cube_koala",
    name: "考拉玩偶",
    url: "/assets/models/3d/prizes/animal-koala.glb",
    category: "plush",
    enabled: true,
    selectionWeight: 5,
    maxPerRound: 2,
    targetHeight: 0.82,
    groundOffset: 0,
    grabRadius: 0.5,
    grabOffset: [0, 0.55, 0],
    collider: { type: "box", size: [0.58, 0.72, 0.54] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "cube_lion",
    name: "小狮玩偶",
    url: "/assets/models/3d/prizes/animal-lion.glb",
    category: "character",
    enabled: true,
    selectionWeight: 4,
    maxPerRound: 2,
    targetHeight: 0.84,
    groundOffset: 0,
    grabRadius: 0.54,
    grabOffset: [0, 0.58, 0],
    collider: { type: "box", size: [0.64, 0.74, 0.58] },
    scaleRange: [0.9, 1.04],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "cube_monkey",
    name: "小猴玩偶",
    url: "/assets/models/3d/prizes/animal-monkey.glb",
    category: "character",
    enabled: true,
    selectionWeight: 4,
    maxPerRound: 2,
    targetHeight: 0.84,
    groundOffset: 0,
    grabRadius: 0.52,
    grabOffset: [0, 0.57, 0],
    collider: { type: "box", size: [0.62, 0.74, 0.56] },
    scaleRange: [0.9, 1.06],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "cube_bee",
    name: "蜜蜂玩偶",
    url: "/assets/models/3d/prizes/animal-bee.glb",
    category: "character",
    enabled: true,
    selectionWeight: 3,
    maxPerRound: 2,
    targetHeight: 0.76,
    groundOffset: 0,
    grabRadius: 0.48,
    grabOffset: [0, 0.5, 0],
    collider: { type: "box", size: [0.56, 0.66, 0.52] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.08, 0.08], y: [-Math.PI, Math.PI], z: [-0.12, 0.12] },
  },
  {
    id: "cube_crab",
    name: "小蟹玩偶",
    url: "/assets/models/3d/prizes/animal-crab.glb",
    category: "character",
    enabled: true,
    selectionWeight: 3,
    maxPerRound: 2,
    targetHeight: 0.72,
    groundOffset: 0,
    grabRadius: 0.5,
    grabOffset: [0, 0.48, 0],
    collider: { type: "box", size: [0.68, 0.62, 0.54] },
    scaleRange: [0.92, 1.08],
    rotationRange: { x: [-0.1, 0.1], y: [-Math.PI, Math.PI], z: [-0.14, 0.14] },
  },
  {
    id: "gift_box_small",
    name: "小礼盒",
    url: "/assets/models/3d/prizes/gift-box-small.glb",
    category: "gift",
    enabled: true,
    selectionWeight: 2,
    maxPerRound: 1,
    targetHeight: 0.54,
    groundOffset: 0,
    grabRadius: 0.38,
    grabOffset: [0, 0.38, 0],
    collider: { type: "box", size: [0.46, 0.46, 0.46] },
    scaleRange: [0.95, 1.12],
    rotationRange: { x: [-0.12, 0.12], y: [-Math.PI, Math.PI], z: [-0.12, 0.12] },
    colorVariants: ["pink", "blue", "sage", "orange"],
  },
  {
    id: "gift_box_wide",
    name: "扁礼盒",
    url: "/assets/models/3d/prizes/gift-box-wide.glb",
    category: "gift",
    enabled: true,
    selectionWeight: 2,
    maxPerRound: 1,
    targetHeight: 0.5,
    groundOffset: 0,
    grabRadius: 0.42,
    grabOffset: [0, 0.36, 0],
    collider: { type: "box", size: [0.62, 0.42, 0.48] },
    scaleRange: [0.95, 1.12],
    rotationRange: { x: [-0.12, 0.12], y: [-Math.PI, Math.PI], z: [-0.12, 0.12] },
    colorVariants: ["cream", "pink", "lavender"],
  },
];

export const COLOR_VARIANTS = {
  cream: "#f4ead4",
  pink: "#f4a8bd",
  blue: "#9ccdf2",
  sage: "#a8c8a1",
  orange: "#efaa63",
  lavender: "#bda8e8",
  caramel: "#b98255",
};
